# Generated by Django 4.2.2 on 2023-08-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing_latitude_listing_longitude_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="listing",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=17, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=17, max_digits=20, null=True
            ),
        ),
    ]
